### ISSUE TITLE
Import date auto format

### ISSUE THREAD

**Issue by JulienGasparLopes** [UgnisSoftware/react-spreadsheet-import#110]
## Problem :

When importing date value there is an auto-formatting doing two things : 
- formatting `DD/MM/YYYY` to `DD/MM/YY` (year is trimmed so there is no difference between 2019 and 1919)
- removing leading 0 so `02/02/2019` is transformed to `2/2/19`

First auto-formatting is a really big deal as data is now "corrupted"
/!\ `uploadStepHook` can't be used to bypass this behavior as data passed to this hook is already corrupted

## Why it happens
I've located the formatting on `mapWorkbook` function during call to `XLSX.utils.sheet_to_json` with param `raw: false` (return of `sheet_to_json` will be formatted to string)
I've found [this thread](https://stackoverflow.com/questions/53163552/format-date-with-sheetjs) that explains how we can handle this thing with a date format
Also from the [documentation of sheetJS](https://docs.sheetjs.com/docs/csf/features/dates) about handling dates

## Solutions proposed

1. We could pass parameter `raw: true` (or allow parametrization) so values wouldn't be parsed to string and we'll be able to use Date object and parse it as we need (but this will force user to format object to string using `uploadStepHook` ...)
2. We could pass parameter `dateNF:'yyyy-mm-dd'` with a default format so date user would be able to parse it using `uploadStepHook`. This format could also be a parameter

Solution n°2 sounds promising 😄 

Thx for reading !
I'm really diving into the lib, thx a lot for you work ;)

**Comment by JulitorK** [comment]
thanks for your contribution, @JulienGasparLopes ⭐ 
Released with v2.0.6
