### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by stefanosala** [UgnisSoftware/react-spreadsheet-import#113]
Hi there! 
Is there any plan / are you working on supporting React 18?

Thanks!

**Comment by stefanosala** [comment]
@masiulis amazing, thanks! Is there any way we can collaborate / help?

**Comment by masiulis** [comment]
Thanks for the offer, but this task can get tricky. Upgrading the react-data-grid library is complicated - it has no documentation. I would also need to debug why, in latest chrome, table scroll became so janky. And webpack/storybook will also need an upgrade to support new versions.

I'll try to find some time for the version upgrade soon.

**Comment by abhishek-butola** [comment]
Any update?

**Comment by mohqarmout** [comment]
any update?

**Comment by mackehansson** [comment]
any update?

**Comment by SpringSan** [comment]
any update?

**Comment by kstrub-fn** [comment]
any update?

**Comment by masiulis** [comment]
Release with >4.0.0
