### ISSUE TITLE
Handle wrong column number on row

### ISSUE THREAD

**Issue by JulienGasparLopes** [UgnisSoftware/react-spreadsheet-import#122]
Hi ! :)

## Problem
When importing file with at least one row that has more columns than the selected header, I got a crash : 
```
normalizeTableData.ts:10 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
at normalizeTableData.ts:10:22
at Array.reduce (<anonymous>)
at normalizeTableData.ts:8:9
at Array.map (<anonymous>)
at normalizeTableData (normalizeTableData.ts:7:8)
at _callee2$ (MatchColumnsStep.tsx:149:22)
at tryCatch (runtime.js:63:40)
at Generator.invoke [as _invoke] (runtime.js:294:22)
at Generator.next (runtime.js:119:21)
at asyncGeneratorStep (main.2816d88b.iframe.bundle.js:1:76136)
```
It can't access column.type as column doesn't exist

## Reproduction
Reproduced on RSI Demo page on google Chrome Version 103.0.5060.53 (Official Build) (x86_64) on macOs
Using this file content and selecting first row as header : 
```
col_one,col_two
1,2,3
```
NB : if you select second row everything works fine

## Solution
I think RSI should handle this case (after header selection) as its goal is file validation
Here are the solutions I can think of (no preference, this is a product decision ;) ) :
- find maximum column and only allow selection of rows that has this maximum column number
- ignore trailing columns as they don't follow the header definition

Thx for reading !

**Comment by JulitorK** [comment]
Hi, @JulienGasparLopes, thanks for submitting this! I made some changes.
It will basically be what you described:
- user selects a row as a header
- trailing columns that don't follow the header definition will get trimmed in the next step

I have released this in v2.0.7

Thanks again for your input!
