### ISSUE TITLE
Custom validators

### ISSUE THREAD

**Issue by jamesicon** [UgnisSoftware/react-spreadsheet-import#128]
Is there anyway to write custom validation logic? I see REQUIRED | REGEX | UNIQUE but was curious if there was a way for something like CUSTOM where a user defines a function for that field that does custom validation logic and returns `true` or `false` sort of like yup does with its `test` functionality. 

Thanks!

**Comment by JulitorK** [comment]
Yes, custom validations can be implemented using hooks. An example here: https://github.com/UgnisSoftware/react-spreadsheet-import#hooks
