### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by eelior** [UgnisSoftware/react-spreadsheet-import#130]
Hey guys, the built it support for translating the UI is perfect! 
How can I also change the UI direction to RTL? (Right-to-Left, for langueges such as Hebrew and Arabic)
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/59517348/183238767-1e19ce1c-a7c3-4d49-82f1-afc823aeabd5.png">

**Comment by eelior** [comment]
I had unsuccessful quick try to add RTL support.
I tried both ways mentioned in the Chakra-UI docs:
https://chakra-ui.com/docs/styled-system/rtl-support#using-rtl-stylis-plugin

The farthest I have come was with the first method in the docs and it only helped me changing the direction of the two first buttons from the demo:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/59517348/183252796-c2fdf4af-a290-4ed2-ba05-ab8935cbe586.png">

But it didnt work for the component itself that stayed the same.

**Comment by masiulis** [comment]
Hey @eelior, I did a quick check, you can add this to theme
```
  customTheme={{
      Modal: {
      baseStyle: {
        dialog: {
          direction: "rtl",
        },
      },
    },
}}
```

With the table we are using (https://github.com/adazzle/react-data-grid) it's a bit more complicated - we need to pass a prop `direction="rtl"`, so we would have to expose this in our props.

The end result would look like this:
<img width="1206" alt="Screenshot 2022-08-07 at 14 02 04" src="https://user-images.githubusercontent.com/5903616/183287634-1353bcf7-71d9-4b82-a549-8c434f5aca8a.png">

Is this something close to what you are trying to achieve?

**Comment by eelior** [comment]
@masiulis This looks perfect!!
I over complicated this, I'm happy to see its so easy with the `customTheme` prop. 
Ill try to make you a PR for the table later this evening.

**Comment by masiulis** [comment]
`rtl` prop is available. Closing this as there should solve the discussed problem.
