### ISSUE TITLE
React state update warning on every import dialog step

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#134]
I get this bit annoying "Can't perform a react state..." warning every time i go to the next step in the import dialog.

![Screenshot 2022-09-23 at 15 35 49](https://user-images.githubusercontent.com/38214863/191972460-0a5c6f91-543d-4848-b360-23ed4b6b8acf.png)

**Comment by masiulis** [comment]
Hey @loeffelr, we are close to being done with React 18v support - it removes this error completely. If you are still using React <=17, you can safely ignore this error.
