### ISSUE TITLE
Provide typescript types and enums

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#135]
Is it possible to provide typescript support in form of types and enums, for example for field, fieldType, validation, ... ?

Would be awesome!

**Comment by masiulis** [comment]
Hey @loeffelr, could you provide an example when TypeScript doesn't work for you? We do provide types for [field](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/types.ts#L57), [fieldType](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/types.ts#L69) and [validation](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/types.ts#L97).

**Comment by loeffelr** [comment]
@masiulis ups, sorry, didn't saw that file, thank you!
