### ISSUE TITLE
rowHook runs on all row

### ISSUE THREAD

**Issue by lucifer-crybaby** [UgnisSoftware/react-spreadsheet-import#137]
As described on the doc rowHook first runs through on all row after that it supposed to run only on the row that changed but it runs on all row making it expensive function

**Comment by alkanna** [comment]
Hello,
I encountered this issue as well so I can confirm.

**Comment by lucifer-crybaby** [comment]
> Hello, I encountered this issue as well so I can confirm.

Hi, thanks for confirming. Hope authors will see this one.

**Comment by masiulis** [comment]
Hey @lucifer-crybaby, @alkanna, thank you for reporting this, we are investigating issues with rowHook.

**Comment by masiulis** [comment]
Fix released with 4.3.0.
