### ISSUE TITLE
onSubmit closes modal

### ISSUE THREAD

**Issue by lucifer-crybaby** [UgnisSoftware/react-spreadsheet-import#138]
If onSubmit is fired the modal closes automatically making it bad UX, example is that if user completes the flow frontend makes request to backend and backend checks if data is correct or is there any data that has already in the DB or something like that and if there is backend will send error to frontend and frontend will display that error notifying to user that there is an error and user will fix that data and sends again but modal closing automatically makes user to re upload sheet everytime if there is an error. I'm not an expert on this one but if there was an option to manually close modal after onSubmit that would be great!

**Comment by masiulis** [comment]
Hey @lucifer-crybaby, thanks for the report, I agree that onSubmit should be able to accept async function. Feel free if you would like to create a PR.

**Comment by masiulis** [comment]
Released in 4.6.0!

**Comment by dcrana** [comment]
Hi @lucifer-crybaby @masiulis  i am facing same UX issue 

`import { ReactSpreadsheetImport } from "react-spreadsheet-import";

const ImportSheet = ({ open, onClose, onSubmit, fields, options = {} }) => {
  return (
    <ReactSpreadsheetImport
      isOpen={open}
      onClose={onClose}
      onSubmit={onSubmit}
      fields={fields}
      options={options}
    />
  );
};

export default ImportSheet;
`

this is my component . could you please help me how you resolved this issue ?
