### ISSUE TITLE
Optimisation issue on mobile

### ISSUE THREAD

**Issue by eliska-lh** [UgnisSoftware/react-spreadsheet-import#142]
The dialogue goes behind the browser's bottom bar on both chrome and safari and you can't proceed.

![IMG_8442](https://user-images.githubusercontent.com/116285384/196966371-2905589d-2cf7-402e-9020-97f29384a0a0.PNG)
![IMG_8443](https://user-images.githubusercontent.com/116285384/196966448-47ba03df-4ed4-4ea0-9823-a4bf331bcd79.PNG)

**Comment by masiulis** [comment]
Released in 4.4.1.
