### ISSUE TITLE
Can't resolve '@chakra-ui/react' , framer-motion, @chakra-ui/theme-tools

### ISSUE THREAD

**Issue by gjeanne-lecab** [UgnisSoftware/react-spreadsheet-import#144]
Hey ! I'm using node version 14.19.3 and npm v 6.14.17

I'm getting lots of errors in my page while compiling my react code : 

Module not found: Error: Can't resolve 'framer-motion' or 'chakra-ui' in '/home/XXX/XXX/app/node_modules/@chakra-ui/menu/dist'
These errors only appears with version 14 of node, if I use version 16 it is working. However for aws servors purposes, I can't use version 16 at the moment. Is there a way to make it work ? 

Also I can see a folder chakra ui being in my node-modules which is weird because the errors says it can't be found.

Thanks :)

**Comment by gjeanne-lecab** [comment]
Fix temporaire : 

suivre les conseils de cette issue : https://github.com/UgnisSoftware/react-spreadsheet-import/issues/115
Qui fera installer chakra v1 et framer-motion manuellement

**Comment by gbrocha** [comment]
One workaround I found was the [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides). 
But it's not the ideal way. The dependencies of this package should be updated.

**Comment by masiulis** [comment]
Sorry for a late reply, this should no longer be an issue with >4.0.0.
