### ISSUE TITLE
Umlauts not displayed correctly when importing .csv file

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#145]
When importing a .csv file all "umlauts", like "ä, ü, ö, ..." gets display incorrect.

<img width="828" alt="image-20221201-102047" src="https://user-images.githubusercontent.com/38214863/205289856-328c6434-c4a9-4e16-8225-b95a5e176fed.png">

I tested this with different sources, like hubspot .csv export, excel .csv export and test-data-generator csv.
All have the same outcome regarding the “umlauts”.
Maybe there's a problem with the charset?

**Comment by masiulis** [comment]
Sorry for a late reply. I can see umlauts are working with .xlsx and .csv (if exported to UTF-16 format) but not with standard .csv UTF-8 files. Underneath we use SheetJS, I don't really see a way to make this work from our side. If anyone would like to investigate, PRs are welcome.

**Comment by JulitorK** [comment]
Fixed with #191.
