### ISSUE TITLE
Customization of ValidateDataStep

### ISSUE THREAD

**Issue by SuperQ8** [UgnisSoftware/react-spreadsheet-import#146]
Hi there,
Just wondering is there anyway to modify the ValidateDataStep as attached screenshot? Basically I need to add a check All checkbox and move the "Delete Selected Rows" button to the bottom.
Thanks,
Quentin
![modify](https://user-images.githubusercontent.com/23289605/205780868-2f3dec6c-5628-42b4-8c9e-b03bed8c89e0.png)

**Comment by masiulis** [comment]
Hey, sorry for a late reply. Sadly, the only way to achieve this would be to fork the project as the requirements are too unique for us to add to the project.
