### ISSUE TITLE
error - react-data-grid 

### ISSUE THREAD

**Issue by mariusiscoding** [UgnisSoftware/react-spreadsheet-import#161]
Using React 17.0.2
After installing I get the error:

ERROR in ./node_modules/react-data-grid/lib/bundle.js 4:0-56

Module not found: Error: Can't resolve 'react/jsx-runtime' in 'C:\Users\...\client\node_modules\react-data-grid\lib'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by masiulis** [comment]
Sorry for a late reply, this is probably caused by your build setup, not the library. This might help [https://github.com/adazzle/react-data-grid/issues/2773](https://github.com/adazzle/react-data-grid/issues/2773).
