### ISSUE TITLE
Page freeze after modal close or error prevented submission

### ISSUE THREAD

**Issue by Zonalds** [UgnisSoftware/react-spreadsheet-import#164]
After closing the pop or after the error message is show. nothing else on the entire page is clickable. Any idea how we could fix this?

**Comment by masiulis** [comment]
Sorry for a late reply, could you share your props configuration and the file you are trying to upload? Could you try the latest versions (>4 for react 18 or >3 for React 17) and see if it's still the case?

**Comment by masiulis** [comment]
Because this issue is quite old, I will close it. Please reopen if it's still a problem.

**Comment by cgcab** [comment]
I had this problem recently and had to use this conf of overrides to make it work @Zonalds 

    "overrides": {
        "@chakra-ui/icon": "3.0.0",
        "@chakra-ui/react": "2.8.2",
        "@chakra-ui/popper": "^3.1.0",
        "@chakra-ui/react-context": "^2.1.0",
        "@chakra-ui/system": "^2.6.2"
    },
