### ISSUE TITLE
error after updating to version 4.0.1

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#174]
<img width="623" alt="Screenshot 2023-05-24 at 11 42 16" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/38214863/bf23b6ad-4e58-47f8-9ed8-4c6c3d39e2bf">

**Comment by masiulis** [comment]
Hey @loeffelr >v4.0.0 supports only React >18. Could you check which version of React you are using?

**Comment by loeffelr** [comment]
using version 17 - what's with version 3? is there the csv fix in it?

https://github.com/UgnisSoftware/react-spreadsheet-import/issues/157

**Comment by masiulis** [comment]
Sadly, no. But I can backport it to v3 later today.

**Comment by loeffelr** [comment]
Would be great, thank you!

**Comment by masiulis** [comment]
@loeffelr could you try v3.1.0?

**Comment by loeffelr** [comment]
Working, thank you!
