### ISSUE TITLE
Close button disappeared

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#175]
After upgrade to v3.1.0 the "close" button in the right top corner is gone. Any idea how that could be possible?

<img width="1728" alt="Screenshot 2023-05-25 at 09 55 10" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/38214863/b1678a60-c665-48d0-9f09-534ab8ae3b8a">

**Comment by masiulis** [comment]
Hey @loeffelr, have you tried inspecting the DOM to see what styles are influencing the close button? There should be no changes in v3 that would affect this button. Could you share your custom theme?

**Comment by loeffelr** [comment]
Okay i was able to fix it a bit hacky with some css overriding, but should be work for now, thank you!

**Comment by masiulis** [comment]
@loeffelr Could you share what hacks you had to add? I wonder if we can fix it from the components side.
