### ISSUE TITLE
 Phasing Out AntD in Favor of Custom/Lighter Components

### ISSUE THREAD

**Issue by hari-bhandari** [UgnisSoftware/react-spreadsheet-import#178]
Hello there,are there any plans to transition from AntD to custom/lighter components due to performance concerns?

**Comment by masiulis** [comment]
Hey @hari-bhandari, do you mean Chakra UI? No, we like Chakra and we are not planning to change it. It would require a complete rewrite and a full component prop API change - it would be easier to start from scratch then.

If you are worried about bundle size, you might want to split RSI into a separate chunk and load it dynamically.
