### ISSUE TITLE
Import not working on Safari

### ISSUE THREAD

**Issue by loeffelr** [UgnisSoftware/react-spreadsheet-import#179]
Unfortunately import isn't working on safari at all. In the second and fourth step i can't see the content properly.

No custom styling or translations.

Tested with different files and versions, working smooth on chrome or firefox.

As we're using React v17 highest version i tested is v3.1.0

<img width="1728" alt="Screenshot 2023-06-21 at 09 44 16" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/38214863/42aa30c7-f02c-4857-9603-dd2da76407d8">
<img width="1728" alt="Screenshot 2023-06-21 at 09 44 05" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/38214863/8e5e6b88-5c2c-4789-b35e-22c174b16ad9">

**Comment by JulitorK** [comment]
thanks for the report, will investigate.

**Comment by loeffelr** [comment]
@JulitorK any updates on this?

**Comment by squirly** [comment]
I can confirm this issue.

Seems the problem is setting `h={0}` here: https://github.com/UgnisSoftware/react-spreadsheet-import/blob/ec05ef1cde4baa5e65eb07980f683e61ea95dadf/src/steps/SelectHeaderStep/SelectHeaderStep.tsx#L35

**Comment by charpun** [comment]
In case it helps anyone trying to open a PR, it would seem that setting `height: initial` on that element resolves the issue.

![Screenshot 2023-08-11 at 2 12 31 PM](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/8062104/43b7c2bc-3b3b-43f8-a18f-771966df2a99)
![Screenshot 2023-08-11 at 2 13 21 PM](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/8062104/c6c9f174-fa2b-4fdd-a70d-76e5305cfc69)
