### ISSUE TITLE
Please send column mapping data onSubmit

### ISSUE THREAD

**Issue by raomohan499** [UgnisSoftware/react-spreadsheet-import#181]
I appreciate  on getting this component to the users. It is really helpful. We want a new feature as can you please send column mapping metadata with submitted data and file info. It will really helpful and valuable for us if you guys get this feature.

const onSubmit = (data: any, file: any , columnmappinginfo : any) =>{
           console.log(columnmappinginfo); //which prints like {'id' : 'ID' , 'name' : 'UserName' .. }

}

**Comment by raomohan499** [comment]
Any Update on this? 

I made some changes to the code, so that we can get column mapping meta data. Follows :


Files :
----------------------------------------------------
src/types.ts
src/steps/UploadFlow.tsx
src/steps/ValidationStep/types.ts
src/steps/ValidationStep/ValidationStep.tsx

Attaching Zip files
-----------------------------------------------------
src/types.ts as src_types.ts
src/steps/UploadFlow.tsx as UploadFlow.tsx
src/steps/ValidationStep/types.ts as validationsteps_types
src/steps/ValidationStep/ValidationStep.tsx as ValidationStep.tsx


I sincere request, please merge this changes to actual package, which gives us simple mapping information.




[MappingInfoFiles.zip](https://github.com/UgnisSoftware/react-spreadsheet-import/files/12838333/MappingInfoFiles.zip)

**Comment by raomohan499** [comment]
@JulitorK @jeffnv  @ineentho  @jtordgeman please look into this new feature.

**Comment by masiulis** [comment]
Hey @raomohan499 this data is already available in `matchColumnsStepHook` - you can store it in a local `useState` and then access it in the `onSubmit` function. PR for this to be part of onSubmit would also be welcome.

**Comment by raomohan499** [comment]
@masiulis , how can I get that data from matchColumnsStepHook, it would more helpful if you refer any example
