### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by gjeanne-lecab** [UgnisSoftware/react-spreadsheet-import#183]
If I import a csv with accent in it (either in the column name or directly in the data). I see an encoding issue with the display and the data sent back to me when the user finishes the validate step.

![test](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/112616826/6663defc-dd17-4459-85d7-6fdbaa2781c5)

**Comment by gjeanne-lecab** [comment]
I did a fork that solve the issue. 

I added the option "codepage: 65001" to the upload step xlsx reader.

**Comment by mmbfreitas** [comment]
Same issue here, would you open a pull request to main repository??

**Comment by JulitorK** [comment]
Closing, as fixed with #191. 
Thank you @gjeanne-lecab  and @mmbfreitas for your contribution.
