### ISSUE TITLE
export 'default' (imported as 'Icon') was not found in '@chakra-ui/icon' (possible exports: Icon, createIcon)

### ISSUE THREAD

**Issue by cgcab** [UgnisSoftware/react-spreadsheet-import#198]
HI there, I am having some trouble since this morning (last friday was working okay) with this error 

```
ERROR in ./node_modules/chakra-react-select/dist/esm/chakra-components/menu.js 229:42-46
export 'default' (imported as 'Icon') was not found in '@chakra-ui/icon' (possible exports: Icon, createIcon)
```

I am using the latest version of the lib :        

```
"react": "^18.0.0",
"react-spreadsheet-import": "^4.1.2",
```

As I was saying last friday I cleaned my `node_module` and remove my `package-lock` to install a clean and up to date version of the app and everything was fine, but it seems there was a change in one of the dependency of this package (cause it's the only one I use that uses Chakra) and now I am getting this error.

I am normally using node 14 and npm 6 as described under :  

```
❯ node --version
v14.19.3

❯ npm --version
6.14.17

ERROR in ./node_modules/chakra-react-select/dist/esm/chakra-components/menu.js 229:42-46
export 'default' (imported as 'Icon') was not found in '@chakra-ui/icon' (possible exports: Icon, createIcon)
```

I also tried updating to node 18 with npm 9 to see if that would solve the error but it didn't

```
❯ node --version
v18.17.1

❯ npm --version
9.6.7

ERROR in ./node_modules/chakra-react-select/dist/esm/chakra-components/menu.js 229:42-46
export 'default' (imported as 'Icon') was not found in '@chakra-ui/icon' (possible exports: Icon, createIcon)`
```

There is a good chance it's linked to this update 
![image](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/57679996/046f619a-6bef-40c8-b177-8c393d39fa15)

Anyone else having this issue, any fix ? 
Thanks a lot

**Comment by anthonycamut** [comment]
Same issue for me

**Comment by gjeanne-lecab** [comment]
Same here as well

**Comment by JulitorK** [comment]
Thanks for report! 
Seems to be a dependency issue: https://github.com/csandman/chakra-react-select/issues/276
We're waiting for update on their end. 

For now you can try to enforce the previous version with
```
  "overrides": {
    "@chakra-ui/icon": "3.0.0"
  },
``` 
You'll need to remove node_modules, package-lock and clean install for it to work.

**Comment by csandman** [comment]
Just updated, everything should be working if you update to [`v4.7.1`](https://github.com/csandman/chakra-react-select/releases/tag/v4.7.1)!

**Comment by anthonycamut** [comment]
Awesome, thank you for you quick fix, it works for me!
