### ISSUE TITLE
Latest release is broken

### ISSUE THREAD

**Issue by KenzoBenzo** [UgnisSoftware/react-spreadsheet-import#200]
The latest release on this repo `^3.1.1` doesn't include any code in the install, and is a version goof. Installing instead `^4.1.2` works as expected. 

<img width="907" alt="image" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/32865577/23d144d5-e293-4a04-816a-8b4221617aed">

**Comment by cgcab** [comment]
yop something went wrong for sure

**Comment by JulitorK** [comment]
thanks for report! A mistake on my end, this was supposed to be a backported version for #182, I fixed it with 3.1.2.  
Please ignore it if you have previously used 4.x.x version.
