### ISSUE TITLE
How use matchColumnsStepHook 

### ISSUE THREAD

**Issue by anthonycamut** [UgnisSoftware/react-spreadsheet-import#203]
Hello,

How use matchColumnsStepHook because when I try to use it i have an error in dataMutation.js in line 17 appears that data is null so I 
have to return something?

Here my sample code

matchColumnsStepHook={(table, rawData, columns) => {
            console.log('matchColumnsStepHook ', table, rawData, columns);            
          }}

Can you provide me an example please?
Thanks

**Comment by masiulis** [comment]
Hey @anthonycamut, there is a hook example [here](https://github.com/UgnisSoftware/react-spreadsheet-import#hooks). And you can see the types [here](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/53668849a93f0ba7b2655c3ccc9e2686d7130e6d/src/types.ts#L19C34-L19C38). 

For this hook you should return the first parameter (`table`) after changing it with your business logic. `rawData` and ` columns` are here so you would have more context for the changes you want to make.
