### ISSUE TITLE
BUG: safari does not render the table correctly after importing a CSV file

### ISSUE THREAD

**Issue by elnygren** [UgnisSoftware/react-spreadsheet-import#206]
<img width="1426" alt="image" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/6632349/5c4b9d54-41a9-41d2-880d-815aa0e3264d">

**Comment by DevGeorge** [comment]
Same issue,
plus the validate data doesn't work either

**Comment by masiulis** [comment]
Hey @elnygren thank you for reporting this, it looks like a duplicate of https://github.com/UgnisSoftware/react-spreadsheet-import/issues/179 - I should be able to investigate safari issues sometime soon.

@DevGeorge is it safari only? Could you create a separate issue?

**Comment by masiulis** [comment]
Issue fixed in the latest release.
