### ISSUE TITLE
Not working with react 17

### ISSUE THREAD

**Issue by SubhasmitaLMG** [UgnisSoftware/react-spreadsheet-import#208]
My project is of react 17 that use custom start script. Imported the package but the issue is that at the time I am using import { ReactSpreadsheetImport } from "react-spreadsheet-import"; this in my code it is showing error in the below.

Failed to compile.

 ./node_modules/@chakra-ui/transition/dist/chunk-RKXMPHPI.mjs
 Can't import the named export 'AnimatePresence' from non EcmaScript module (only default export is available)

**Comment by masiulis** [comment]
Hey @SubhasmitaLMG, you should use [react-spreadsheet-import v3.x.x](https://github.com/UgnisSoftware/react-spreadsheet-import/tree/v3) - we are still maintaining that version for folks using React 17 / React 16.
