### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by abhishekchauhan-ipseity** [UgnisSoftware/react-spreadsheet-import#214]
User can search so, deletion or edit any cell is quite easy for us.
thanks

**Comment by masiulis** [comment]
Hey @abhishekchauhan-ipseity I am sorry but we are not planning to add search functionality anywhere in the flow, as it seems to specific for some usecase you have. Feel free to fork the project and if you find a way to make this reusable PRs are always welcome!
