### ISSUE TITLE
Select dropdown should be auto filled

### ISSUE THREAD

**Issue by SubhasmitaLMG** [UgnisSoftware/react-spreadsheet-import#223]
Can I make select dropdown as auto select, no need to fill it up at "select header row" stage manually.

<img width="1728" alt="Screenshot 2023-11-16 at 6 23 54 PM" src="https://github.com/UgnisSoftware/react-spreadsheet-import/assets/143089771/31440808-636d-4e4c-9fa1-2421e0693f89">

**Comment by masiulis** [comment]
Hey @SubhasmitaLMG what are the props you are sending to the component? Have you passed `autoMapSelectValues={true}`?

**Comment by SubhasmitaLMG** [comment]
NO,Where to use this autoMapSelectValues={true}? 
Could you please help.

I am using select like this only.
{
    label: "Team",
    key: "team",
    alternateMatches: ["department"],
    fieldType: {
      type: "select",
      options: [
        { label: "Team One", value: "one" },
        { label: "Team Two", value: "two" },
      ],
    },
  },

**Comment by SubhasmitaLMG** [comment]
Hey @masiulis got the solution now.Thank you.

**Comment by LalithShankar** [comment]
had an similar issue, worked for me too, thanks for this @masiulis and @SubhasmitaLMG.
define autoMapSelectValues in the return of React Spreadsheet Import Props and also define it in interface of that .js file
