### ISSUE TITLE
Add support for material-ui

### ISSUE THREAD

**Issue by bryanjtc** [UgnisSoftware/react-spreadsheet-import#229]
It would be nice to support other ui libraries like material-ui.
The core logic of the components, hooks and utils should be separated to allow using them with material-ui or other ui libraries.
Steps to follow:
1. Convert to monorepo
2. Separate core logic from components
3. Split `react-spreadsheet-import` package into `react-spreadsheet-import/chakra-ui`,` react-spreadsheet-import/material-ui`, `react-spreadsheet-import/core`.

> The idea is inspired by what DevExtremeReactive does: https://github.com/DevExpress/devextreme-reactive/tree/master/packages

**Comment by masiulis** [comment]
Hey @bryanjtc thank you for the suggestion but we are not planning to do that. Feel free to fork the project though!
