### ISSUE TITLE
Set value for all rows in a column

### ISSUE THREAD

**Issue by Tobias235** [UgnisSoftware/react-spreadsheet-import#230]
If there is no data in any of the rows of specific column (Group), we want to be able to select a group that would be set for all rows. Is this possible to achieve?

**Comment by masiulis** [comment]
It would looks something like 
```
      <ReactSpreadsheetImport
        {...mockRsiValues}
        isOpen={isOpen}
        onClose={onClose}
        onSubmit={setData}
        matchColumnsStepHook={(table, rawData, columns) => {
          /* your logic here: */
          const newTable = table.map((row) => row)
          return newTable
        }}
      />
```

**Comment by Tobias235** [comment]
Thank you for quick answer. As this is on click to next step, We need to have a select dropdown, that is visible if no groups before click on next as we dont want to hardcode the group

**Comment by masiulis** [comment]
@Tobias235 I don't think I understand the problem, could you explain it a bit more or give an example?

**Comment by Tobias235** [comment]
How to map undefined values?

After uploading a file sometimes the user gives empty cells. We need a way to map empty cells to some value. 

Currently when a cell is undefined , it does not show up in the "match columns tab"

**Comment by masiulis** [comment]
@Tobias235 I am sorry, but I still don't understand the use case. I would suggest to investigate other hooks or if nothing matches what you need, feel free to fork the project!
