### ISSUE TITLE
xlsx-ugnis incorrect data check error while installing on Mac

### ISSUE THREAD

**Issue by priyadhanz** [UgnisSoftware/react-spreadsheet-import#234]
Error below while installing react-spreadsheet-import package using yarn on Mac.

yarn add react-spreadsheet-import                   
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/xlsx-ugnis/-/xlsx-ugnis-0.20.3.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/priya/ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by masiulis** [comment]
Hey @priyadhanz, we don't use yarn ourselves, so can't really help you out with this problem. If you figure out what could be changed in https://github.com/UgnisSoftware/xlsx-ugnis - feel free to create a PR.
