### ISSUE TITLE
Sucess message in modal

### ISSUE THREAD

**Issue by SubhasmitaLMG** [UgnisSoftware/react-spreadsheet-import#235]
@masiulis After submission is there any way to add success message in a modal.

**Comment by masiulis** [comment]
Hey @SubhasmitaLMG, successful onSubmit will close the modal. If the submit was successful you could show a toast from your side. It would looks something like :

```tsx
<ReactSpreadsheetImport
  ...
  onSubmit={(data) => {
     return fetch(<submit data>)
        .then(() => {
           // you can use useToast from chakra-ui or any other toast library you have
           toast(<your toast message>)
        })
  }} 
/>
```
