### ISSUE TITLE
Incorrect step indicator if "initialStepState" is provided

### ISSUE THREAD

**Issue by samy-mssi** [UgnisSoftware/react-spreadsheet-import#250]
Hi,

Just noticed this issue, when I provide the prop "initialStepState". Seems like https://github.com/UgnisSoftware/react-spreadsheet-import/issues/171  (that was solved)

Got the issue on version 4.6.1
sandbox link : https://codesandbox.io/p/sandbox/lucid-panna-43xql6

screenshot 1
![image](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/151582118/6f5df2c4-af29-4664-a9ac-a464a86875b7)
screenshot 2 
![image](https://github.com/UgnisSoftware/react-spreadsheet-import/assets/151582118/b6e9b68b-a561-457f-9c9a-6f9221d8b3e6)
(back button doesn't work, but I can access to "match columns" step by hitting the "3" button in the Stepper, after this, everything is fine)

**Comment by agnar-nomad** [comment]
+1
I also see this issue, however the variation of mine is exactly as in #171 .

**Comment by agnar-nomad** [comment]
I am not sure if this is appropriate but it looks like an issue might be here:
`utils/steps.ts` > line 25 > `return Math.min(0, steps.indexOf(step))` seems to work correctly when changed to `return Math.max(0, steps.indexOf(step))`

**Comment by lroudge** [comment]
This issue is still happening apparently, any news on when it could be fixed?

**Comment by agnar-nomad** [comment]
> This issue is still happening apparently, any news on when it could be fixed?

It seems the maintainer is no longer active on this repo. I had to fork it and fix it myself.

**Comment by masiulis** [comment]
Fix released in v4.7.1.
