### ISSUE TITLE
Back Functionality missing

### ISSUE THREAD

**Issue by faizan-zahid-arhamsoft** [UgnisSoftware/react-spreadsheet-import#261]
During the import wizard if the user needs to go back to the previous step say from the data editing to the column mapping there is no such functionality available. Kindly add it to make it more user friendly

**Comment by masiulis** [comment]
Hey @faizan-zahid-arhamsoft have you tried adding prop `isNavigationEnabled`? [https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/types.ts#L29](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/types.ts#L29)
