### ISSUE TITLE
Support for defaultProps will be removed

### ISSUE THREAD

**Issue by Finkes** [UgnisSoftware/react-spreadsheet-import#262]
As already commented in #156 I still see the same warning using v4.6.1 in a fresh next.js@v14.2.2 app. Any ideas?

> Warning: ReactSpreadsheetImport: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by masiulis** [comment]
Hey @Finkes, can you try out v4.7.0?

**Comment by Finkes** [comment]
Thank you @masiulis for your quick support! v4.7.0 solves the issue for me.
