### ISSUE TITLE
Is there a way to conditionally render select options.

### ISSUE THREAD

**Issue by bytesagar** [UgnisSoftware/react-spreadsheet-import#264]
I was trying to make two columns select one column options depends upon the other. Basically i need to filter the options in second select from the value selected in first select column. Is it possible?

**Comment by masiulis** [comment]
Hey @bytesagar I don't think that's possible, you would need to fork the project.

**Comment by bytesagar** [comment]
Hello @masiulis. Is there any way that I can access column value inside fielts.fieldType.options? I tried playing with the code but was not able to.
