### ISSUE TITLE
Is it possible to make autoMapSelectValues case-insensitive?

### ISSUE THREAD

**Issue by henriquealtoe** [UgnisSoftware/react-spreadsheet-import#268]
Is it possible to make autoMapSelectValues case-insensitive? It works well, but it doesn’t automatically recognize user inputs when they’re entered in camel case.

Example attached
![case-sensitive-error](https://github.com/user-attachments/assets/ff6621b8-5d43-4267-b263-bd8b768055af)

**Comment by masiulis** [comment]
Hey @henriquealtoe, as far as I remember field has `alternateMatches` where you could manually or programatically add different variations of the field name.

**Comment by henriquealtoe** [comment]
Hi @masiulis, thank you very much for your quick reply. I may be doing something wrong, but I couldn't get `alternateMatches `to work with selected fields, they only worked here with column mapping.
![Imagem do WhatsApp de 2024-10-31 à(s) 09 18 38_e76aee40](https://github.com/user-attachments/assets/44502969-c400-426c-a457-91199ec104e8)
