### ISSUE TITLE
Deleting rows results in future updates 

### ISSUE THREAD

**Issue by sb8244** [UgnisSoftware/react-spreadsheet-import#84]
I seem to have stumbled across a bug that results after deleting a row and then editing a row further in the import.

```js
      const changes = changedData?.indexes.reduce((acc, val) => {
        const realIndex = rows[val].__index
        acc[realIndex] = rows[val]
        return acc
      }, {} as Record<number, typeof data[number]>)
      const newData = Object.assign([], data, changes)
      updateData(newData)
```

Let's say that there are 3 rows `[0, 1, 2]`. Row `0` is deleted. If `1` is changed, then `data[0]` should be updated because the old first record is deleted. However, `acc[realIndex]=` causes the changes to reference the old `__index` value, so `data[1]` gets updated and overwrites the data stored there.

**Comment by masiulis** [comment]
Great, thanks for finding this! Your solution works but I would like to refactor indexing as it's quite messy. All indexing should be done in the hook function and `addIndexes` probably should mutate not spread object. Will solve this with the other issue.

**Comment by sb8244** [comment]
No problem at all! I always assume that the author will see a better way to handle the problem based on their goals and knowledge of the project.

If you're looking at indexing and data...one thing that would be useful is the ability to asynchronously add errors to the import. My intention there is to submit data rows to the backend for giving a warning if they already exist (mine is an upsert import).

**Comment by masiulis** [comment]
For the second part we could make hooks accept promises so that data transformations and adding errors would be async.

It would look something like:
```jsx
rowHook={async (row, addError) => {
  const resp = await fetch(...)
  if(resp.error){
    addError(...)
  }
  return row
}}
```

But this would mean we also need to add spinning loader to cell. It's a bit bigger refactoring, not sure when I would have time for this. For now, if there aren't millions of rows and data is not private, you could fetch all primary keys beforehand and store it locally.

**Comment by alkanna** [comment]
@masiulis Sorry for borrowing this issue but is there a way right now to do external data validation then ?
I would like to check for something against an API for each row, but without an async hook I'm not sure how I need to go about it !
