### ISSUE TITLE
use custom Theme does not work everywhere?

### ISSUE THREAD

**Issue by pcace** [UgnisSoftware/react-spreadsheet-import#88]
Hi there, 

i am trying to get custom themes to work with your Package. is there any description what styles are editable and what are not? 
the theme i am using for example defines buttonprops. These styles are not reflected. (for example this violet "select file" button should appear white, but doesnt. 

Any idea where i am not on the right track ;) ?

Thank you so much!

**Comment by masiulis** [comment]
Hey @pcace, everything should be fully customisable, if it's not then that's a bug :) You can see all keys here [https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/theme.ts#L54](https://github.com/UgnisSoftware/react-spreadsheet-import/blob/master/src/theme.ts#L54)

 
To change "Select button" specifically you can target it with 
```jsx
    <ReactSpreadsheetImport
        {...mockRsiValues}
        isOpen={isOpen}
        onClose={onClose}
        onSubmit={setData}
        customTheme={{
          components: {
            UploadStep: {
              baseStyle: {
                dropzoneButton: {
                  bg: "red",
                },
              },
            },
          },
        }}
      />
```
<img width="1182" alt="Screenshot 2022-04-13 at 10 21 58" src="https://user-images.githubusercontent.com/5903616/163123694-5b79179e-037e-4f9d-b1a9-6078f758bb7e.png">

Or you can change all buttons at the same time (use the latests package - in upload step color was enforced before)

```jsx
    <ReactSpreadsheetImport
        {...mockRsiValues}
        isOpen={isOpen}
        onClose={onClose}
        onSubmit={setData}
        customTheme={{
          components: {
            Button: {
              baseStyle: {
                borderRadius: "none",
              },
              defaultProps: {
                colorScheme: "yellow",
              },
            },
          },
        }}
      />
```
<img width="1191" alt="Screenshot 2022-04-13 at 11 04 30" src="https://user-images.githubusercontent.com/5903616/163130213-82f955b4-5081-49e0-8f43-8857d480dacd.png">

Or to change theme colors globally
```jsx
    <ReactSpreadsheetImport
        {...mockRsiValues}
        isOpen={isOpen}
        onClose={onClose}
        onSubmit={setData}
        customTheme={{
          colors: {
            rsi: {
              500: "teal",
            },
          },
        }}
      />
```
<img width="1189" alt="Screenshot 2022-04-13 at 10 24 34" src="https://user-images.githubusercontent.com/5903616/163123718-15c05ad8-243b-4a81-8141-c47216047468.png">

Hope this explains the different approaches that you can use :)
