### ISSUE TITLE
Columns Cannot be Duplicated

### ISSUE THREAD

**Issue by tzarger** [UgnisSoftware/react-spreadsheet-import#91]
I agree this is a good message, just not sure it Is this supposed to look like this? Is there a way to style this?

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1757589/163226189-74cdc11a-b6a9-4d6e-82f5-1bfe0d5aba1a.png">

**Comment by masiulis** [comment]
We use the default chakra toast. Is there ChakraProvider outside our component that could be messing the styles? I am not sure how to reproduce this.

**Comment by masiulis** [comment]
Seems like it was a package version mismatching issue.
